---
strategy: polling
no_screen_padding: ''
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://aviationweather.gov/api/data/metar?format=geojson&ids={{ station }}
polling_headers: ''
polling_body: 
id: 21542
custom_fields:
- keyname: station
  field_type: string
  name: Station ICAO ID
- keyname: units
  field_type: select
  name: Units
  options:
    - 'icao'
    - 'us'
  default: 'icao'
  description: "ICAO: °C, hPa, nautical miles. US: °F, inHg, statute miles."
name: METAR
refresh_interval: 60
