name: Create Release

on:
  push:
    tags:
      - "v*" # Runs when a tag starting with "v" is pushed

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP file with selected files
        run: |
          zip -r release.zip \
            full.liquid \
            half_horizontal.liquid \
            half_verticval.liquid \
            quadrant.liquid \
            settings.yml

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false
